version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=store_development 
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  web:
    build: .
    entrypoint: ['bash', 'bin/docker-entrypoint']
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    tty: true
    volumes:
      - .:/rails
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/store_development
      - REDIS_URL=redis://redis:6379

  sidekiq:
    build: .
    entrypoint: ['bash', 'bin/docker-entrypoint']
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/rails
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/store_development
      - REDIS_URL=redis://redis:6379

  test:
    build: .
    entrypoint: ['bash', 'bin/docker-entrypoint']
    command: bundle exec rspec
    volumes:
      - .:/rails
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgresql://postgres:password@db:5432/store_test # DB de teste separado
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data: